[Feat] 이벤트 추가하기 버튼을 눌렀을때 발생하는 오류 해결
Error: useCalendarDataActions should be used within CalendarDataProvider

ReferenceError: Property 'useContext' doesn't exist

TypeError: Cannot read property 'addEvent' of undefined, js engine: hermes

"이벤트 추가하기" 버튼을 눌렀을 때 나타나는 오류를 해결하였습니다.
버튼을 눌렀을때 이미지 Url과 텍스트 입력들이 잘 입력되는 것을 콘솔로 확인하였습니다.
아직 eId가 업데이트 되지않는 것과 날짜 정보까지 포함하도록하는 문제가 남아있습니다.